version: "3.2"
services:
  pyapp:
    build: .
    environment:
     - REDIS_HOST:redis
     - REDIS_PORT:6379
    depends_on:
     - redis
    ports:
      - 8888:8888
    networks:
     - backend
  redis:
    image: redis:alpine
    command: redis-server # --requirepass adminPASS
    expose:
      - 6379
    ports:
     - 6379:6379
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
     - REDIS_REPLICATION_MODE=master
    networks:
     - backend
# networking for the Redis container
networks:
  backend:
    driver: bridge
